In [9]:
from __future__ import absolute_import, division, print_function, unicode_literals
import pathlib
import pandas as pd
import numpy as np

"""Load data """
#df = pd.read_excel(r'C:\Users\anotator\Desktop\VALIDACE_KPI\data\evidence\honda\HSC.xlsx')
df = pd.read_excel('/home/evzen/Downloads/HSC.xlsx')
df2 = df.loc[:,["File name", "Status (annotatable or not annotatable and reason)",
       "Time of first validation", "Date of first validation", "Date of second validation",
       "Date of third validation", 'Annotation Ratio NET/1500fr [min]', '[min] per 1 dyn.obj.',
       'Annotation Ratio RB/1500fr. [min]', "Validation Ratio", "Stav videa (info pro logistika a validátory)"
        ]]

In [10]:
df1 = df.loc[:,["File name", "Status (annotatable or not annotatable and reason)",
                "Date of first validation", "Date of second validation", "Date of third validation", 
                'Annotation Ratio NET/1500fr [min]', '[min] per 1 dyn.obj.',
       'Annotation Ratio RB/1500fr. [min]', "Validation Ratio", "Stav videa (info pro logistika a validátory)"
        ]]

df1["File name"] = df1["File name"].isna() == True

my_array = df1[df1["File name"]==True].index
myarray = np.array([7])
for x in my_array:

    nan_file = df.iloc[x, 0]
    y = x + 1
    #print(y)
    row_below = df.iloc[y, 0]
    #print(row_below)
    nan_x = "nan"
    
    if row_below == nan_x:
        y += 1
        
    else:
        df2.iloc[x, 0] = row_below
        #print(nan_file1)

In [11]:
ndf = df2[df2["Stav videa (info pro logistika a validátory)"] == "Zvalidované a validátorem uložené v archivu"]
ndf = ndf[ndf["Status (annotatable or not annotatable and reason)"] == "Annotatable"]
ndf = ndf.drop(["Status (annotatable or not annotatable and reason)", "Stav videa (info pro logistika a validátory)"], axis=1)
#ndf = ndf.set_index("Annotation Ratio NET/1500fr [min]")


ndf["Date of first validation"] = ndf["Date of first validation"].astype(str)
ndf["Date of second validation"] = ndf["Date of second validation"].astype(str)
ndf["Date of third validation"] = ndf["Date of third validation"].astype(str)



ndf1 = ndf.loc[(ndf['Date of first validation'] == "2019-07-16 00:00:00")]
ndf2 = ndf.loc[(ndf['Date of second validation'] == "2019-07-16 00:00:00")]
ndf3 = ndf.loc[(ndf['Date of third validation'] == "2019-07-16 00:00:00")]
ndf4 = pd.concat([ndf1,ndf2,ndf3])
ndf4.head(70)

,File name,Time of first validation,Date of first validation,Date of second validation,Date of third validation,Annotation Ratio NET/1500fr [min],[min] per 1 dyn.obj.,Annotation Ratio RB/1500fr. [min],Validation Ratio
2126,20190629_060441_ecu_2019-06-29_060539_085_part...,00:30:00,2019-07-16 00:00:00,nan,nan,149.900067,NaN,74.950033,NaN
2129,20190629_085939_ecu_2019-06-29_090919_813_part...,00:18:00,2019-07-16 00:00:00,nan,nan,66.910786,NaN,49.933422,NaN
2166,20190701_133603_ecu_2019-07-01_133930_165_part...,00:30:00,2019-07-16 00:00:00,nan,nan,148.093842,NaN,0.000000,NaN
2167,20190701_133603_ecu_2019-07-01_133930_165_part...,00:20:00,2019-07-16 00:00:00,nan,nan,347.803070,NaN,142.932769,NaN
2170,20190702_191651_ecu_2019-07-02_192720_292_part...,00:30:00,2019-07-16 00:00:00,nan,nan,36.666667,NaN,0.000000,NaN
2172,20190702_191651_ecu_2019-07-02_192720_292_part...,00:35:00,2019-07-16 00:00:00,nan,nan,58.921438,NaN,28.961385,NaN
2174,20190702_191651_ecu_2019-07-02_192720_292_part...,00:30:00,2019-07-16 00:00:00,nan,nan,65.956029,NaN,0.000000,NaN
2176,20190705_022134_ecu_2019-07-05_022251_095_part...,00:30:00,2019-07-16 00:00:00,nan,nan,144.927536,NaN,65.217391,NaN
2181,20190705_024510_ecu_2019-07-05_024529_248_part...,00:30:00,2019-07-16 00:00:00,nan,nan,130.573248,NaN,47.770701,NaN
2182,20190705_025406_ecu_2019-07-05_025439_816_part...,00:35:00,2019-07-16 00:00:00,nan,nan,79.946702,NaN,44.970020,NaN
2184,20190705_025406_ecu_2019-07-05_025439_816_part...,00:30:00,2019-07-16 00:00:00,nan,nan,76.566125,NaN,41.763341,NaN
2186,20190705_025406_ecu_2019-07-05_025439_816_part...,00:30:00,2019-07-16 00:00:00,nan,nan,102.256700,NaN,31.734838,NaN
2188,20190705_025406_ecu_2019-07-05_025439_816_part...,00:20:00,2019-07-16 00:00:00,nan,nan,127.914723,NaN,59.960027,NaN
2190,20190705_025406_ecu_2019-07-05_025439_816_part...,00:20:00,2019-07-16 00:00:00,nan,nan,83.944037,NaN,23.984011,NaN
2192,NaN,00:20:00,2019-07-16 00:00:00,nan,nan,115.503080,NaN,46.201232,NaN
2195,20190705_025406_ecu_2019-07-05_025439_816_part...,00:30:00,2019-07-16 00:00:00,nan,nan,114.231318,NaN,28.557830,NaN
2197,20190705_025406_ecu_2019-07-05_025439_816_part...,00:30:00,2019-07-16 00:00:00,nan,nan,146.902065,NaN,0.000000,NaN
2199,20190705_025406_ecu_2019-07-05_025439_816_part...,00:30:00,2019-07-16 00:00:00,nan,nan,109.926716,NaN,64.956696,NaN
2201,20190705_025406_ecu_2019-07-05_025439_816_part...,00:15:00,2019-07-16 00:00:00,nan,nan,111.925383,NaN,0.000000,NaN
2202,20190705_025406_ecu_2019-07-05_025439_816_part...,00:30:00,2019-07-16 00:00:00,nan,nan,206.185567,NaN,73.883162,NaN
2204,20190705_025406_ecu_2019-07-05_025439_816_part...,00:30:00,2019-07-16 00:00:00,nan,nan,58.960693,NaN,0.000000,NaN
2206,20190705_025406_ecu_2019-07-05_025439_816_part...,00:40:00,2019-07-16 00:00:00,nan,nan,151.273885,NaN,0.000000,NaN
2208,20190705_025406_ecu_2019-07-05_025439_816_part...,00:35:00,2019-07-16 00:00:00,nan,nan,96.104562,NaN,0.000000,NaN
2209,20190705_025406_ecu_2019-07-05_025439_816_part...,00:30:00,2019-07-16 00:00:00,nan,nan,122.646584,NaN,41.958042,NaN
2210,20190705_025406_ecu_2019-07-05_025439_816_part...,00:30:00,2019-07-16 00:00:00,nan,nan,133.910726,NaN,69.953364,NaN
2211,20190705_025406_ecu_2019-07-05_025439_816_part...,00:30:00,2019-07-16 00:00:00,nan,nan,153.126670,NaN,68.145377,NaN
2212,20190705_025406_ecu_2019-07-05_025439_816_part...,00:30:00,2019-07-16 00:00:00,nan,nan,144.341801,NaN,51.963048,NaN
2213,20190705_033557_ecu_2019-07-05_035458_012_part...,00:08:00,2019-07-16 00:00:00,nan,nan,112.500000,NaN,75.000000,NaN
2214,20190705_045807_ecu_2019-07-05_045927_638_part...,00:20:00,2019-07-16 00:00:00,nan,nan,94.936709,NaN,59.960027,NaN
2216,20190705_045807_ecu_2019-07-05_045927_638_part...,00:10:00,2019-07-16 00:00:00,nan,nan,68.993506,NaN,40.584416,NaN
...,...,...,...,...,...,...,...,...,...
2227,20190707_003633_ecu_2019-07-07_003737_177_part...,00:15:00,2019-07-16 00:00:00,nan,nan,74.035990,NaN,39.331620,NaN
2228,20190707_003633_ecu_2019-07-07_003737_177_part...,00:30:00,2019-07-16 00:00:00,nan,nan,80.000000,NaN,75.000000,NaN
2229,20190707_003633_ecu_2019-07-07_003737_177_part...,00:25:00,2019-07-16 00:00:00,nan,nan,99.575146,NaN,47.796070,NaN
2230,20190707_003633_ecu_2019-07-07_003737_177_part...,00:20:00,2019-07-16 00:00:00,nan,nan,74.950033,NaN,39.973351,NaN
2278,20190705_025406_ecu_2019-07-05_025439_816_part...,00:31:00,2019-07-16 00:00:00,nan,nan,80.307263,NaN,25.139665,NaN
2287,20190705_045807_ecu_2019-07-05_045927_638_part...,00:20:00,2019-07-16 00:00:00,nan,nan,129.913391,NaN,69.953364,NaN
2291,20190705_045807_ecu_2019-07-05_045927_638_part...,00:30:00,2019-07-16 00:00:00,nan,nan,120.481928,NaN,50.200803,NaN
2356,20190707_003633_ecu_2019-07-07_003737_177_part...,00:25:00,2019-07-16 00:00:00,nan,nan,51.846591,NaN,46.164773,NaN
2416,20190705_025406_ecu_2019-07-05_025439_816_part...,00:20:00,2019-07-16 00:00:00,nan,nan,148.900733,NaN,50.966023,NaN
2114,20190629_060441_ecu_2019-06-29_060539_085_part...,NaN,nan,2019-07-16 00:00:00,nan,209.860093,NaN,0.000000,NaN
2124,20190629_060441_ecu_2019-06-29_060539_085_part...,NaN,nan,2019-07-16 00:00:00,nan,55.925433,NaN,0.000000,NaN
2132,20190629_094619_ecu_2019-06-29_100322_209_part...,NaN,nan,2019-07-16 00:00:00,nan,111.637348,NaN,0.000000,NaN
2139,NaN,NaN,nan,2019-07-16 00:00:00,nan,32.483157,NaN,0.000000,NaN
2146,20190629_150156_ecu_2019-06-29_150320_999_part...,NaN,nan,2019-07-16 00:00:00,nan,72.951366,NaN,0.000000,NaN
2148,20190701_133603_ecu_2019-07-01_133930_165_part...,NaN,nan,2019-07-16 00:00:00,nan,71.904128,NaN,0.000000,NaN
2150,20190701_133603_ecu_2019-07-01_133930_165_part...,NaN,nan,2019-07-16 00:00:00,nan,39.973351,NaN,0.000000,NaN
2157,20190701_133603_ecu_2019-07-01_133930_165_part...,NaN,nan,2019-07-16 00:00:00,nan,42.763158,NaN,0.000000,NaN
2159,20190701_133603_ecu_2019-07-01_133930_165_part...,NaN,nan,2019-07-16 00:00:00,nan,29.980013,NaN,0.000000,NaN
2161,20190701_133603_ecu_2019-07-01_133930_165_part...,NaN,nan,2019-07-16 00:00:00,nan,69.906791,NaN,0.000000,NaN
2163,20190701_133603_ecu_2019-07-01_133930_165_part...,NaN,nan,2019-07-16 00:00:00,nan,78.947368,NaN,0.000000,NaN
2168,20190702_174658_ecu_2019-07-02_174950_100_part...,NaN,nan,2019-07-16 00:00:00,nan,53.996824,NaN,6.352567,NaN
2178,20190705_023656_ecu_2019-07-05_023907_275_part...,NaN,nan,2019-07-16 00:00:00,nan,33.814247,NaN,0.000000,NaN
2180,20190705_024510_ecu_2019-07-05_024529_248_part...,NaN,nan,2019-07-16 00:00:00,nan,125.000000,NaN,31.250000,NaN
2193,20190705_025406_ecu_2019-07-05_025439_816_part...,NaN,nan,2019-07-16 00:00:00,nan,41.581109,NaN,0.000000,NaN
2215,20190705_045807_ecu_2019-07-05_045927_638_part...,NaN,nan,2019-07-16 00:00:00,nan,29.980013,NaN,0.000000,NaN
2118,20190629_060441_ecu_2019-06-29_060539_085_part...,NaN,nan,nan,2019-07-16 00:00:00,52.034261,NaN,0.000000,NaN
2137,20190629_111021_ecu_2019-06-29_111853_842_part...,NaN,nan,nan,2019-07-16 00:00:00,22.459165,NaN,0.000000,NaN
2140,20190629_142642_ecu_2019-06-29_142726_402_part...,NaN,nan,nan,2019-07-16 00:00:00,40.423484,NaN,0.000000,NaN
2144,20190629_150156_ecu_2019-06-29_150320_999_part...,NaN,nan,nan,2019-07-16 00:00:00,21.482730,NaN,0.000000,NaN
2154,20190701_105156_ecu_2019-07-01_105944_246_part...,NaN,nan,nan,2019-07-16 00:00:00,37.949401,NaN,0.000000,NaN

In [201]:
sum(df2["File name"].isna() == True)

0

In [38]:
ndf5 = ndf4.drop_duplicates("Annotation Ratio NET/1500fr [min]")

In [27]:
df.iloc[2126,-11]

10.0

In [35]:
myn1array = ndf5.index
myn1array

Int64Index([2126, 2129, 2166, 2167, 2170, 2172, 2174, 2176, 2181, 2182, 2184,
            2186, 2188, 2190, 2192, 2195, 2197, 2199, 2201, 2202, 2204, 2206,
            2208, 2209, 2210, 2211, 2212, 2213, 2214, 2216, 2217, 2218, 2220,
            2221, 2222, 2223, 2225, 2226, 2227, 2228, 2229, 2230, 2278, 2287,
            2291, 2356, 2416, 2114, 2124, 2132, 2139, 2146, 2148, 2157, 2159,
            2161, 2163, 2168, 2178, 2180, 2193, 2118, 2137, 2140, 2144, 2154],
           dtype='int64')

In [77]:
ndf6 = df.iloc[myn1array,:]
ndf6 = ndf6.drop(["Start date ", "Start time", "Comment", "Finish date", "Finish time", "Annotator's name",
                 "Status (annotatable or not annotatable and reason)", "Break (čas strávený na přestávkách)",
                 "Net time spent on video manipulation, clarifications, internal meetings (anotátor)",
                  "Time for annotation corrections after not succeful validation", "File name", 
                 "Net time spent on video (Dyn. objects)", "Net time spent on video (RB)",
                  "Annotation time in seconds. Automatic formula", "Number of objects (počet oanotovaných objektů dynamika)",
                  "Number of frames", "Net time spent on video (total)", "Ready for validation", "Validation time",
                  "Results of second validation", "Time of first validation", "Name of first validator", 
                 "Results of first validation", "Repair notes after second validation","Time of second validation ", 
                 "Repair notes after first validation", "Name of second validator", "Time of third validation", "Name of third validator", 
                  "Results of third validation", "Repair notes after third validation", "Net time spent on video manipulation, clarifications, internal meetings (validátor)",
                 "Stav videa (info pro logistika a validátory)", "Čas práce A vč. přestávek (hod.)", 
                  "Čas práce V (hod.) efektivní", "Čas práce V (hod.) total", "Finish time - start time",
                  "Rozdíl AQ vs. AO (kontrola pro anotátora)", "Annotation Ratio NET/1500fr [min] filter"], axis=1)
ndf6.head(2)

,Date of first validation,Date of second validation,Date of third validation,Annotation Ratio NET/1500fr [min],[min] per 1 dyn.obj.,Annotation Ratio RB/1500fr. [min],Validation Ratio
2126,2019-07-16 00:00:00,NaN,NaN,149.900067,10.0,74.950033,29.980013
2129,2019-07-16 00:00:00,NaN,NaN,66.910786,8.5,49.933422,17.976032

In [170]:
ndf8 = ndf6.rename(columns={"Annotation Ratio NET/1500fr [min]" : "Annotation Ratio",
                            "[min] per 1 dyn.obj.": "Dyn obj./min", 
                            "Annotation Ratio RB/1500fr. [min]": "Annotation Ratio RB" })
ndf9 = pd.DataFrame(ndf8.mean())

Annotation Ratio        96.758881
[min] per 1 dyn.obj.     8.500128
Annotation Ratio RB     31.446848
Validation Ratio        24.108635
Name: 0, dtype: float64

In [172]:
menaar = ndf6["Annotation Ratio NET/1500fr [min]"].mean()
meanvr = ndf6["Validation Ratio "].mean()
#mean1dyn = ndf6["[min] per 1 dyn.obj."].mean()
#print((meanvr + menaar))
#print(mean1dyn)

In [194]:
ndf7 = pd.DataFrame(columns=np.array(ndf6.columns))
ndf7 = ndf7.rename(columns={"Annotation Ratio NET/1500fr [min]" : "Annotation Ratio",
                            "[min] per 1 dyn.obj.": "Dyn obj./min", 
                            "Annotation Ratio RB/1500fr. [min]": "Annotation Ratio RB" })
ndf7 = ndf7.drop(["Date of first validation", "Date of second validation", "Date of third validation"], axis=1)
ndf7.insert(0,"Date", "2019-07-16")
ndf7["Annotation Ratio"] = 96.758881
ndf7.insert(5, "Total Ratio", sum(ndf7["Annotation Ratio"] + ndf7["Validation Ratio "]))
ndf7

Empty DataFrame
Columns: [Date, Annotation Ratio, [min] per 1 dyn.obj., Annotation Ratio RB, Validation Ratio , Total Ratio]
Index: []

In [ ]:
import numpy as np
import pandas as pd
# Create some sample data
df = pd.DataFrame({"A": np.random.randn(5), "B": np.random.randn(5)}) 
# Sum the columns:
sum_row = {col: df[col].sum() for col in df}
# Turn the sums into a DataFrame with one row with an index of 'Total':
sum_df = pd.DataFrame(sum_row, index=["Total"])
# Now append the row:
df = df.append(sum_df)

In [87]:
df

              A         B
0     -0.023379  2.631158
1      1.837959 -1.070710
2      0.548561 -0.727035
3     -0.429892  0.215743
4     -1.805681 -0.156108
Total  0.127569  0.893048

In [210]:
df.loc["2019-07-16", :] == True

KeyError: 'the label [2019-07-16] is not in the [index]'