In [1]:
!pip install simpledbf

Collecting simpledbf
  Downloading https://files.pythonhosted.org/packages/8a/d3/e4c25cd8f739dd7ddd19c255cd5552e08cdd439ac51a36ae12640ce8a748/simpledbf-0.2.6.tar.gz
Building wheels for collected packages: simpledbf
  Running setup.py bdist_wheel for simpledbf: started
  Running setup.py bdist_wheel for simpledbf: finished with status 'done'
  Stored in directory: C:\Users\anotator\AppData\Local\pip\Cache\wheels\72\dd\df\cdfb970a508ef9750ebb4b6e035a3410c3d62b5a6a91d2aafc
Successfully built simpledbf
Installing collected packages: simpledbf
Successfully installed simpledbf-0.2.6

In [10]:
import pandas as pd
from simpledbf import Dbf5

dbf = Dbf5(r"C:\Users\anotator\Desktop\VALIDACE_KPI\data\dataset\obce1991\OBCE111.DBF", codec = "CP852")

df = dbf.to_dataframe()
df.to_csv(r"C:\Users\anotator\Desktop\VALIDACE_KPI\data\dataset\obce1991\OBCE111.csv")
df.head()

,KOD_NUTS,KOD_OKR_91,POR_OBCE,KOD_OBCE,NAZEV_OBCE,U8,U10,U11,U12,U13,...,U57,U58,U59,U60,U61,U62,U63,U64,U65,U66
0,CZ0100,3100,001,554782,Praha,328893,9,21378,36,9465,...,250471,12689,219187,82625,26100,39022,17503,176,1214174,724174
1,CZ0211,3201,001,529303,Benešov,4450,0,259,1,85,...,2374,76,3682,1072,406,522,144,1,15892,7141
2,CZ0211,3201,002,532568,Bernartice,70,0,5,0,0,...,55,2,47,16,7,7,2,0,246,156
3,CZ0211,3201,003,530743,Bílkovice,57,0,6,0,0,...,53,0,33,16,11,5,0,0,206,121
4,CZ0211,3201,004,532380,Blažejovice,32,0,1,0,1,...,39,2,22,6,3,3,0,0,134,79